services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - project-master
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "pnpm dev" # pnpx prisma db push && 
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - project-master
    volumes:
      - .:/app
      - /app/node_modules
      - .prisma:/app/.prisma
      - ./.env:/app/.env
    environment:
      DATABASE_URL: postgres://postgres:master@db:5432/master?schema=public
      # Auth configuration
      BETTER_AUTH_SECRET: "${BETTER_AUTH_SECRET}"
      # BETTER_AUTH_URL: "${BETTER_AUTH_URL}"
      # NEXT_PUBLIC_API_BASE_URL: "${NEXT_PUBLIC_API_BASE_URL}"
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .git/**
            - node_modules/**
            - .next/**
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./pnpm-lock.yaml

volumes:
  pgdata:


networks:
  project-master:
    driver: bridge
